[package]
name = "rust-web-demo"
version = "0.1.0"
edition = "2018"

[dependencies]
diesel = { version = "1.4.8", features = ["postgres"] }
dotenv = "0.13.0"
serde = "1.0.79"
serde_json = "1.0.27"
serde_derive = "1.0.79"

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]