apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
  - image: docker.io/webmakaka/rust-web-demo
    context: ../app
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.rs'
          dest: .
deploy:
  kubectl:
    manifests:
    - ../k8s/*
